spring:
    datasource:
        url: jdbc:postgresql://localhost:4567/testDB
        username: myuser
        password: mypassword
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
    application:
        name: rent-service
        
    servlet:
        multipart:
            enabled: true
            max-file-size: 10MB
            max-request-size: 10MB

eureka:
    client:
        # enabled: false
        service-url:
            defaultZone: http://34.87.57.233:8761/eureka/
        instance:
            prefer-ip-address: true
            instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
            lease-renewal-interval-in-seconds: 5
            lease-expiration-duration-in-seconds: 10
           



# eureka:
#   client:
#     service-url:
#       defaultZone: http://localhost:8761/eureka/