spring:
    datasource:
        url: jdbc:postgresql://localhost:4567/testDB
        username: myuser
        password: mypassword
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
    application:
        name: rent-service

eureka:
    client:
        enabled: false
#         service-url:
#             defaultZone: http://localhost:8761/eureka/



# eureka:
#   client:
#     service-url:
#       defaultZone: http://localhost:8761/eureka/